---
- hosts: cocolarp
  become: 'yes'
  gather_facts: 'no'
  vars:
    username: victor
  vars_files:
    - vars/vault.yml
  roles:
    - role: django-uwsgi
      du_package: backent
      du_repository: namafutatsu/backent
      du_server_name: api.cocolarp.com
      du_port: 8000
      du_env:
        DJANGO_SETTINGS_MODULE: "backent.settings"
        SECRET_KEY: "{{backent.secret_key}}"
        DATABASE_URL: "postgis://postgres:@127.0.0.1:5432/backent"
        ALLOWED_HOSTS: "api.cocolarp.com,127.0.0.1"
        CORS_ORIGIN_WHITELIST: "cocolarp.com"

    - role: register-letsencrypt
      hw_server_name: api.cocolarp.com

    - role: django-https-website
      dhw_server_name: api.cocolarp.com
      dhw_port: 8000

    - role: register-letsencrypt
      hw_server_name: cocolarp.com

    - role: static-https-website
      shw_server_name: cocolarp.com
