---
- hosts: all
  become: 'yes'
  gather_facts: 'no'
  vars:
    username: victor
  vars_files:
    - vars/vault.yml
  roles:
    - role: register-letsencrypt
      hw_server_name: fampintantana.fr

    - role: wordpress
      w_project: fampintantana
      w_server_name: fampintantana.fr
      w_repository: namafutatsu/fampintantana
      w_mysql_user: wordpress
      w_mysql_password: "{{fampintantana.mysql_password}}"
