---
- hosts: laflaque
  become: 'yes'
  gather_facts: 'no'
  vars:
    username: victor
  vars_files:
    - vars/vault.yml
  roles:
    - role: register-letsencrypt
      tags:
        - frontend
        - certs
      rle_server_name: tarot.laflaque.fr

    - role: static-https-website
      tags: frontend
      shw_server_name: tarot.laflaque.fr
